### ISSUE TITLE
Using this repo for add i18n support for ZMI?

### ISSUE THREAD

**Issue by macagua** [zopefoundation/zope.app.locales#9]
Hi @icemac @mgedmin and guys

I am working in this issue https://github.com/zopefoundation/Zope/issues/631 for add the i18n support for ZMI from Zope 4, I would like to using this package for distribute the Zope translations, then there are any comments or suggestions that I should take into account for this improvement?

**Comment by icemac** [comment]
To quote myself from zopefoundation/Zope#631:

> I am not sure if `zope.app.locales` is the right place to store the translations of the ZMI. As @hannosch said in 7669068: „Zope2 uses almost none of the translations provided in the package“. This is still true for Zope 4. Maybe we should have an extra package for the ZMI of Zope and the ecosystem.

How about a package name like `zmi.locales`? (I could create it for you.)

**Comment by d-maurer** [comment]
Michael Howitz wrote at 2019-5-22 23:12 -0700:
> ...
>How about a package name like `zmi.locales`?

Why a separate package? Why not a folder `locales` in the current `Zope`
package, either beside the `docs` folder or (even better) in the `zmi`
subfolder?

**Comment by icemac** [comment]
@d-maurer wrote:
> Why a separate package? Why not a folder `locales` in the current `Zope` package, either beside the `docs` folder or (even better) in the `zmi` subfolder?

Because this `locales` package should also contain the translations for the zope ecosystem.
IMHO Zope should not depend on its ecosystem for this. I do not want to couple Zope and its ecosystem too much.

Alternatively Zope could contain the translations for the message ids it provides in a local `zmi.locales` package but this would not solve the problem for the ecosystem. I'd not like to heave each package its own translations, this would prevent synergies and make translation more difficult. So this would require an additional package. Why not put the Zope translations there, too?

**Comment by icemac** [comment]
I am closing this old issue. Feel free to re-open it if there are any news about the topic.
